version: '3.1'

services:
  prova:
    image: postgres:10-alpine
    container_name: "prova"
    restart: always
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: musica
    volumes:
      - ./banco-dados/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-prova-compose-network


  adminer_postgres:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres-prova-compose-network


networks:
  postgres-prova-compose-network:
    driver: bridge
